### ISSUE TITLE
Check on Milestone #3

### ISSUE THREAD

**Issue by yetson0** [block-bites/fondant-app#16]
### Scope: Basic functionalities via UI + Built-in blockexplorer functionalities

This version of an app should handle some basic functionalities like spinning the network from the UI, and getting the network basic config data (ports, num of blocks, last block, peers etc).

Basic Blockexplorer functionalities so that users can browse deploys and emitted blocks as well as see basic accounts information in the app.

### For Scope 1;

User can;
Install the app through the installer
Control (start / stop / reset) the network from the UI
Browse network configuration
Download node operators keys

### For Scope 2;

Implemented build-in event store where you can browse all passed events (Events tab)
Implemented Deploys view (listing all of the deploys with filtering for WASM ones or Session code)
Filtering in every view
Possibility to dump the data to csv / JSON format

---

DoD:
based on README.md install app and check if it is working.

- [ ] provide feedback in comments

**Comment by peter-blockbites** [comment]
old scope
