### ISSUE TITLE
Responsive CSS to allow the grids to expand/contract

### ISSUE THREAD

**Issue by devendran-m** [block-bites/fondant-app#74]

**Comment by wojtek-blockbites** [comment]
Could you be more specific?
We improved responsiveness. It will be added with next release.
Something like this: 
https://github.com/block-bites/fondant-app/assets/107482064/05476469-cda1-40fb-980c-72dc9c89fe10

**Comment by peter-blockbites** [comment]
@devendran-m could you check now?

**Comment by peter-blockbites** [comment]
Closing as won't do.
