### ISSUE TITLE
I can access /account and all other pages when network is not initialized

### ISSUE THREAD

**Issue by peter-blockbites** [block-bites/fondant-app#85]
use `check-status` cmd?

**Comment by CommonDrum** [comment]
POST to http://localhost:3001/run/cctl-infra-net-status

you will get:


{
    "status": "success",
    "stdout": "validator-group-1:cctl-node-1    RUNNING   pid 635, uptime 0:09:47\nvalidator-group-1:cctl-node-2    EXITED    Mar 27 10:07 AM\nvalidator-group-1:cctl-node-3    RUNNING   pid 633, uptime 0:09:47\nvalidator-group-2:cctl-node-4    RUNNING   pid 672, uptime 0:09:46\nvalidator-group-2:cctl-node-5    RUNNING   pid 671, uptime 0:09:46\nvalidator-group-3:cctl-node-10   STOPPED   Not started\nvalidator-group-3:cctl-node-6    STOPPED   Not started\nvalidator-group-3:cctl-node-7    STOPPED   Not started\nvalidator-group-3:cctl-node-8    STOPPED   Not started\nvalidator-group-3:cctl-node-9    STOPPED   Not started\n",
    "stderr": ""
}
